### ISSUE TITLE
All controller types share the same USB PID

### ISSUE THREAD

**Issue by mathieulh** [bootsector/LLOAD#4] opened 2020-01-25 21:37 UTC
All controller types share the same USB PID, this causes issues when mapping usb controllers on the MiSTer main menu as mapping one controller overwrites the previous mapping of another as all controllers, regardless of types/number of buttons... are detected as the same controller; using a different PID per controller type would fix this.

Here is an example of 2 LLOAD instances using a SATURN and a SNES controller respectively:

[  409.018380] usb 1-1.7: USB disconnect, device number 8
[  748.401583] usb 1-1.7: new full-speed USB device number 9 using dwc2
[  748.505909] usb 1-1.7: New USB device found, idVendor=045e, idProduct=028e, bcdDevice= 1.14
[  748.505969] usb 1-1.7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  748.505977] usb 1-1.7: Product: LLOAD - Low Latency Open Adapter
[  748.505984] usb 1-1.7: Manufacturer: www.brunofreitas.com
[  748.505989] usb 1-1.7: SerialNumber: 1.0
[  748.508384] XPAD: original out.bInterval=1 -> new interval=1
[  748.508393] XPAD: original in.bInterval=1 -> new interval=1
[  748.508856] input: Microsoft X-Box 360 pad as /devices/platform/soc/ffb40000.usb/usb1/1-1/1-1.7/1-1.7:1.0/input/input9

[  876.218384] usb 1-1.2: USB disconnect, device number 3
[  877.681857] usb 1-1.2: new full-speed USB device number 10 using dwc2
[  877.783101] usb 1-1.2: New USB device found, idVendor=045e, idProduct=028e, bcdDevice= 1.14
[  877.783112] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  877.783119] usb 1-1.2: Product: LLOAD - Low Latency Open Adapter
[  877.783126] usb 1-1.2: Manufacturer: www.brunofreitas.com
[  877.783132] usb 1-1.2: SerialNumber: 1.0
[  877.785749] XPAD: original out.bInterval=1 -> new interval=1
[  877.785758] XPAD: original in.bInterval=1 -> new interval=1
[  877.786275] input: Microsoft X-Box 360 pad as /devices/platform/soc/ffb40000.usb/usb1/1-1/1-1.2/1-1.2:1.0/input/input10

The firmware code would need to be adapted to not use the fixed descriptors found here: 

https://github.com/bootsector/LLOAD/blob/master/firmware/Output/USB/Descriptors.c

**Comment by bootsector** [comment] 2020-01-25 23:58
What kind of issues are you having with this? This is by design. Changing PID is not ideal since it will require a USB disconnection/connection every time you change controllers. This is something I don't want LLOAD to have.

**Comment by mathieulh** [comment] 2020-01-26 01:24
The main issue is that MiSTer OSD uses PID to differentiate between controllers, so if you use a genesis  or saturn 6 button controller, map the controls on the MiSTer main menu, then use a SNES controller and map the controls again, finally switch back to your genesis/saturn controllers, buttons used in the OSD won't be the same because the remapping of your SNES controller will have overwritten the mapping configuration for your Genesis/Saturn one.

**Comment by bootsector** [comment] 2020-01-26 01:44
For that you should rely on LLOAD's own pad abstraction default mapping. So, for example, if you map SNES buttons B and A for CANCEL and ENTER respectively, those will be B and C on a Saturn pad (and B and A for a NES pad, and A and B for a NeoGeo CD pad, and so on...)

**Comment by mathieulh** [comment] 2020-01-26 01:47
That's pretty much what I am doing but it is both kind of confusing and annoying, especially to average users who wouldn't understand why their controller configurations keep changing, realistically resetting the usb stack after controller detection would take less than a second and likely be imperceptible to the end user.

**Comment by bootsector** [comment] 2020-02-08 22:20
As discussed previously, I'm closing this because:

1- This behavior is by design

2- LLOAD is a unique USB device. Hence it should have a single VID:PID as per standard

3- There's no "clean" way to change the PID. Also, Windows has issues with some PIDs not issued by Microsoft.

**Closed as completed by bootsector** 2020-02-08 22:20 UTC
